# You can freely choose which server to run. They don't depend on one another.
# This file gives an example config for both games.

services:
  ets2-server:
    image: lshallo/ets2-convoy-server
    # image: ghcr.io/lshallo/ets2-convoy-server # GitHub container registry
    container_name: ets2-server
    restart: unless-stopped
    tty: true
    network_mode: host # important to make game appear in server list
    # if you want to join via direct join token (displayed in logs on startup) you can use port mapping
    # the game will not appear in server list because the server can't determine the external IP
    #ports:
    #  - "27015:27015"
    #  - "27016:27016"
    #  - "27015:27015/udp"
    #  - "27016:27016/udp"
    # volumes:
    # Server files. (executable, libraries)
    # Only mount if you know what you are doing. Can lead to permissions issues.
    #  - "/opt/ets2-server/game-data:/app"
    # Only needed when using custom server_packages.sii and server_packages.dat.
    # Also keeps banlist. If you want to persist the banlist mount this folder.
    #  - "/opt/ets2-server/save-data:/home/steam/.local/share/Euro Truck Simulator 2"
    environment:
      - "ETS_SERVER_UPDATE_ON_START=true"
      - "ETS_SERVER_NAME=My Server"
      - "ETS_SERVER_DESCRIPTION=My server description"
      - "ETS_SERVER_WELCOME_MESSAGE=Welcome to my server!"
      - "ETS_SERVER_PASSWORD=abc123"
      - "ETS_SERVER_MAX_PLAYERS=8"
      - "ETS_SERVER_PORT=27015"
      - "ETS_SERVER_QUERY_PORT=27016"
      # more variables...

  ats-server:
    image: lshallo/ats-convoy-server
    # image: ghcr.io/lshallo/ats-convoy-server # GitHub container registry
    container_name: ats-server
    restart: unless-stopped
    tty: true
    network_mode: host # important to make game appear in server list
    # if you want to join via direct join token (displayed in logs on startup) you can use port mapping
    # the game will not appear in server list because the server can't determine the external IP
    #ports:
    #  - "27015:27015"
    #  - "27016:27016"
    #  - "27015:27015/udp"
    #  - "27016:27016/udp"
    # volumes:
    #  - "/opt/ats-server/game-data:/app" # server files
    #  - "/opt/ats-server/save-data:/home/steam/.local/share/American Truck Simulator" # Only needed when using custom server_packages.sii and server_packages.dat
    environment:
      - "ETS_SERVER_UPDATE_ON_START=true"
      - "ETS_SERVER_NAME=My Server"
      - "ETS_SERVER_DESCRIPTION=My server description"
      - "ETS_SERVER_WELCOME_MESSAGE=Welcome to my server!"
      - "ETS_SERVER_PASSWORD=abc123"
      - "ETS_SERVER_MAX_PLAYERS=8"
      - "ETS_SERVER_PORT=27015"
      - "ETS_SERVER_QUERY_PORT=27016"
      # more variables...

  discord-monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: ets2-discord-monitor
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - DISCORD_CONNECT_ICON=${DISCORD_CONNECT_ICON}
      - DISCORD_DISCONNECT_ICON=${DISCORD_DISCONNECT_ICON}
      - DISCORD_CONNECT_TEXT=${DISCORD_CONNECT_TEXT}
      - DISCORD_DISCONNECT_TEXT=${DISCORD_DISCONNECT_TEXT}
      - MONITOR_CONTAINER_NAME=${MONITOR_CONTAINER_NAME}
    # Monitor watches logs from the container specified in MONITOR_CONTAINER_NAME
    # To monitor a different server, change MONITOR_CONTAINER_NAME in the .env file

